//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARRO()
        {
            this.RESERVACION1 = new HashSet<RESERVACION>();
        }
    
        public int CAR_ID { get; set; }
        public Nullable<int> MAR_ID { get; set; }
        public Nullable<int> MOD_ID { get; set; }
        public string CAR_ESTADO { get; set; }
        public string CAR_PLACA { get; set; }
        public Nullable<int> SED_ID { get; set; }
        public Nullable<int> LOT_ID { get; set; }
        public Nullable<int> RES_ID { get; set; }
    
        public virtual LOTE LOTE { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual MODELO MODELO { get; set; }
        public virtual RESERVACION RESERVACION { get; set; }
        public virtual SEDE SEDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVACION> RESERVACION1 { get; set; }
    }
}
