//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int EMP_ID { get; set; }
        public int SED_ID { get; set; }
        public int PUES_ID { get; set; }
        public int EMP_CEDULA { get; set; }
        public string EMP_NOMBRE { get; set; }
        public string EMP_APELLIDO { get; set; }
        public string EMP_TELEFONO { get; set; }
        public string EMP_RESIDENCIA { get; set; }
        public string EMP_ESTADO { get; set; }
    
        public virtual PUESTO PUESTO { get; set; }
        public virtual SEDE SEDE { get; set; }
    }
}
