//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public int PROVE_ID { get; set; }
        public Nullable<int> SED_ID { get; set; }
        public string PROVE_NOMBRE { get; set; }
        public string PROVE_FUNCION { get; set; }
    
        public virtual SEDE SEDE { get; set; }
    }
}
