//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVACION()
        {
            this.CARRO = new HashSet<CARRO>();
        }
    
        public int RES_ID { get; set; }
        public int LOT_ID { get; set; }
        public int USU_ID { get; set; }
        public int CAR_ID { get; set; }
        public System.DateTime RES_FECHA_INI { get; set; }
        public System.DateTime RES_FECHA_FIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRO> CARRO { get; set; }
        public virtual CARRO CARRO1 { get; set; }
        public virtual LOTE LOTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
